[theme]
base="light"
primaryColor = "#4682b4"
backgroundColor = "#FFFAF0"
secondaryBackgroundColor="#F0EEE6"
font="serif"
baseRadius = "0.8rem"
borderColor = "#4682b4"
showWidgetBorder = true
chartCategoricalColors = ["#4682b4", "#F0EEE6"]
textColor = "#003366"

